# Generated by Django 4.2.3 on 2023-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
