# Generated by Django 4.2.3 on 2023-07-31 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
