# Generated by Django 4.2.3 on 2023-07-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0002_alter_projectphoto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
