# Generated by Django 4.2.3 on 2023-07-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0004_remove_project_tag_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='images',
            new_name='project_image',
        ),
        migrations.RenameField(
            model_name='projectphoto',
            old_name='project_image',
            new_name='images',
        ),
    ]
