# Generated by Django 4.2.3 on 2023-08-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0004_remove_project_tags_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='razer_project.tag'),
        ),
    ]
