# Generated by Django 4.2.3 on 2023-07-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0007_alter_projectphoto_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='razer_project.project'),
        ),
    ]
