# Generated by Django 4.2.4 on 2023-08-30 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('razer_project', '0008_alter_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
