# Generated by Django 4.2.3 on 2023-07-31 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='Description 1')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Description 2')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
