# Generated by Django 4.2.3 on 2023-08-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razer_blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created']},
        ),
    ]
